server:
  port: 8083

spring:
  application:
    name: ms-logistics
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:BD_DAW}
    username: ${DB_USER:cibertec}
    password: ${DB_PASSWORD:cibertec}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:cibertec}
    password: ${RABBIT_PASSWORD:cibertec}

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 3000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info
